services:
# Banco de Dados
  db:
    image: mysql:8.0
    restart: always
    container_name: cont_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: Full_stack
      MYSQL_USER: grupo_03
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u grupo_03 -p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

# Minha Api
  api: 
    build: .
    ports:
      - 5002:5002
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  
      DB_PORT: 3306
      DB_NAME: Full_stack
      DB_USER: grupo_03
      DB_PASSWORD: 12345

  web:
    container_name: web_f
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql+pymysql://atelie_user:atelie_pass@db:3306/atelie
      FLASK_ENV: development


volumes:
  mysql_data: 

